ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: 7d6b970cbd3c216353cb22b383b70c150140662e  # HEAD ; no recent tags
    hooks:
      - id: git-secrets
        entry: git-secrets
        args: [--scan, --recursive]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      # On Windows, git will convert all CRLF to LF,
      # but only after all hooks are done executing.
      # yamllint will fail before git has a chance to convert
      # line endings, so it must be explicitly done before yamllint
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'LF' character
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-ast
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # v1.5.6
    hooks:
      - id: remove-tabs
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 5030dca3047414c338091455ac41803200ec1f0f  # 0.37.3
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: 1880d3752044754d2b88f3aa32e44620e02092fe  # v0.1.0
    hooks:
      - id: dockerfilelint
